esphome:
  name: mini-display-tv-yellow
  friendly_name: Mini Display TV - Yellow

esp8266:
  board: esp01_1m

external_components:
  - source:
      type: git
      url: https://github.com/rletendu/esphome.git
      ref: st7789_nobuffer_202312
    components: [st7789v]

logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
    
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Cardputer Fallback Hotspot"
    password: !secret ap_password

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  interface: hardware
  id: spihwd

output:
  - platform: esp8266_pwm
    pin: GPIO05
    frequency: 1000 Hz
    id: pwm_output
    inverted: true

light:
  - platform: monochromatic
    name: "Backlight"
    output: pwm_output
    id: backlight
    restore_mode: RESTORE_AND_ON

font:
  - file: "gfonts://Orbitron"
    id: dspfont
    size: 69

  - file: "gfonts://Orbitron"
    id: dspfont_small
    size: 26

  - file: "gfonts://Orbitron"
    id: dspfont_medium
    size: 38

color:
  - id: color_white
    red: 100%
    green: 100%
    blue: 100%
  - id: color_green
    red: 0%
    green: 100%
    blue: 0%

time:
  - platform: homeassistant
    id: esptime

switch:
  - platform: homeassistant
    id: air_purifier_outlet1
    entity_id: switch.air_purifier_outlet1

display:
  - platform: st7789v
    model: "Custom"
    spi_id: spihwd
    height: 240
    width: 240
    offset_height: 0
    offset_width: 0
    dc_pin: GPIO00
    reset_pin: GPIO02
    eightbitcolor: true
    update_interval: 30s
    id: disp
    spi_mode: mode3
    lambda: |-
      Color text_color = id(color_white);
      if (id(air_purifier_outlet1).state) {
        text_color = id(color_green);
      }
      // Display the time in 12-hour format
      it.strftime(0, 80, id(dspfont), text_color, TextAlign::BASELINE_LEFT, "%l:%M", id(esptime).now());
      
      // Display the date in abbreviated weekday, MM/DD format (no year)
      it.strftime(0, 140, id(dspfont_medium), text_color, TextAlign::BASELINE, "%a %m/%d", id(esptime).now());
      
      // Display "Party mode: ON" or "No fun allowed"
      if (id(air_purifier_outlet1).state) {
        it.printf(0, 230, id(dspfont_small), text_color, TextAlign::BASELINE_LEFT, "Party mode: ON");
      } else {
        it.printf(0, 230, id(dspfont_small), text_color, TextAlign::BASELINE_LEFT, "No fun allowed");
      }      
